### ISSUE TITLE
Issue making directories in wrong order

### ISSUE THREAD

**Issue by placer14** [BakedSoftware/silica#19]
mikegreenberg [6:34 PM] 
I don't know if you're lurking, but for some reason silica is complaining about a build folder missing:
```exec error: Error: Command failed: silica build -s ./vendor/dd-assets/styles -d ./src/post_build.sh
fs.js:895
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: ENOENT: no such file or directory, mkdir 'build/views/components/partials'
    at Object.fs.mkdirSync (fs.js:895:18)
    at preprocessView (/usr/lib/node_modules/silica/src/cli/silica-build.js:83:8)
    at Object.<anonymous> (/usr/lib/node_modules/silica/src/cli/silica-build.js:99:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
```

[6:36] 
Here's probably the issue... my dir struct:
```  ▾ views/
    ▾ components/
      ▾ partials/
          product_list.html
        side_cart.html
        side_customer.html
        vendor_card.html
```
Alphabetically, the paritals/product_list would be compiled before components/* would.

[6:36] 
Adding a file like so fixed it:
```
    ▾ components/
      ▾ partials/
          product_list.html
        a.html
        side_cart.html
        side_customer.html
        vendor_card.html
```

**Comment by kayleg** [comment]
This should be fixed now
