### ISSUE TITLE
Silica Watch rebuild fails because rmdir fails

### ISSUE THREAD

**Issue by jeffhoye** [BakedSoftware/silica#5]
OS: Win 10, cygwin

I believe it's the node server holding the file handle, because stopping the server and running silica build works.

Here's a possibly related issue?  One user was binding to the wrong event.
https://github.com/gruntjs/grunt-contrib-clean/issues/34

I'm happy to help debug this, but I don't know where to look.

$ silica watch
Rebuilding...
Starting Build

C:\Users\jeffh\AppData\Roaming\npm\node_modules\silica\node_modules\rimraf\rimraf.js:312
        throw er
        ^

Error: ENOTEMPTY: directory not empty, rmdir 'C:\code\go\src\github.com\deliverydudes\console.go.deliverydudes.com\build\bower_components\font-awesome'
    at Error (native)
    at Object.fs.rmdirSync (fs.js:886:18)
    at rmkidsSync (C:\Users\jeffh\AppData\Roaming\npm\node_modules\silica\node_modules\rimraf\rimraf.js:342:11)
    at rmdirSync (C:\Users\jeffh\AppData\Roaming\npm\node_modules\silica\node_modules\rimraf\rimraf.js:332:7)
    at rimrafSync (C:\Users\jeffh\AppData\Roaming\npm\node_modules\silica\node_modules\rimraf\rimraf.js:303:9)
    at C:\Users\jeffh\AppData\Roaming\npm\node_modules\silica\node_modules\rimraf\rimraf.js:340:5
    at Array.forEach (native)
    at rmkidsSync (C:\Users\jeffh\AppData\Roaming\npm\node_modules\silica\node_modules\rimraf\rimraf.js:339:26)
    at rmdirSync (C:\Users\jeffh\AppData\Roaming\npm\node_modules\silica\node_modules\rimraf\rimraf.js:332:7)
    at rimrafSync (C:\Users\jeffh\AppData\Roaming\npm\node_modules\silica\node_modules\rimraf\rimraf.js:303:9)

exec error: Error: Command failed: silica build
C:\Users\jeffh\AppData\Roaming\npm\node_modules\silica\node_modules\rimraf\rimraf.js:312
        throw er
        ^

Error: ENOTEMPTY: directory not empty, rmdir 'C:\code\go\src\github.com\deliverydudes\console.go.deliverydudes.com\build\bower_components\font-awesome'
    at Error (native)
    at Object.fs.rmdirSync (fs.js:886:18)
    at rmkidsSync (C:\Users\jeffh\AppData\Roaming\npm\node_modules\silica\node_modules\rimraf\rimraf.js:342:11)
    at rmdirSync (C:\Users\jeffh\AppData\Roaming\npm\node_modules\silica\node_modules\rimraf\rimraf.js:332:7)
    at rimrafSync (C:\Users\jeffh\AppData\Roaming\npm\node_modules\silica\node_modules\rimraf\rimraf.js:303:9)
    at C:\Users\jeffh\AppData\Roaming\npm\node_modules\silica\node_modules\rimraf\rimraf.js:340:5
    at Array.forEach (native)
    at rmkidsSync (C:\Users\jeffh\AppData\Roaming\npm\node_modules\silica\node_modules\rimraf\rimraf.js:339:26)
    at rmdirSync (C:\Users\jeffh\AppData\Roaming\npm\node_modules\silica\node_modules\rimraf\rimraf.js:332:7)
    at rimrafSync (C:\Users\jeffh\AppData\Roaming\npm\node_modules\silica\node_modules\rimraf\rimraf.js:303:9)

**Comment by jeffhoye** [comment]
the work around is to kill the server and rebuild every time
