### ISSUE TITLE
Install cli names are the wrong name

### ISSUE THREAD

**Issue by jeffhoye** [BakedSoftware/silica#6]
Win 10, cygwin

After an update install, the .js file names in the npm repo are the wrong names.  

Workaround is to rename all 4 files in this directory: add '-cli' to the file name:
'C:\Users\me\AppData\Roaming\npm\node_modules\silica\src\cli\'

$ silica build
module.js:457
    throw err;
    ^

Error: Cannot find module 'C:\Users\me\AppData\Roaming\npm\node_modules\silica\src\cli\silica-cli-build'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by jeffhoye** [comment]
https://github.com/gatsbyjs/gatsby/issues/80

**Comment by jeffhoye** [comment]
https://github.com/tj/commander.js/pull/327

**Comment by jeffhoye** [comment]
I think the fix is just to rename the following in src/
```
silica-build.js >> silica-cil-build.js
silica-create.js >> silica-cil-create.js
silica-watch.js >> silica-cil-watch.js
```
But please try on the mac to make sure it doesn't break it there.
